#pragma once
inline const char *LangDE = R"====(
{
  "Age":"Alter",
  "AgeGlyc":"Alter der Glukose",
  "Compte":"Konto",
  "Display":"Anzeige",
  "Infos":"Informationen",
  "Lang":"Sprache",
  "F_Hor":"Zeitzone",
  "Apropos":"Über",
  "Restart":"Neustart",
  "InitWifi":"WLAN-Initialisierung",
  "Version":"Version: ",
  "Nom_WiFi": "WLAN-Netzwerk: ",
  "MotDePasse":"Passwort: ",
  "RechercheWiFi":"WLAN-Suche:",
  "ConnectedWiFi":"Verbunden über WLAN, IP-Adresse: ",
  "ou":" oder ",
  "EchecWiFi":"WLAN-Verbindung fehlgeschlagen",
  "SelectWifi":"WLAN auswählen",
  "ScanStart":"Netzwerksuche läuft",
  "ScanTermine":"Suche abgeschlossen",
  "PasReseau":"Kein WLAN-Netzwerk gefunden",
  "reseauxTrouves":" Netzwerke gefunden",
  "WaitGluco":"Warten auf Glukosewert",
  "ConfNul":"Unvollständige Konfiguration",
  "LoginFailed":" Keine Verbindung zu Libreview, HTTP-Code: ",
  "LastGlyco":" Letzter bekannter Glukosewert: ",
  "le":" am ",
  "GlucoFailed":" Keine Glukosedaten von Libreview, HTTP-Code: ",
  "GraphFailed":" Kein Diagramm von Libreview, HTTP-Code: ",
  "NoRecentGluco":"Keine aktuellen Glukosewerte",
  "LinkUpIndefini":"LibreLinkUp-Konto nicht definiert",
  "ZoneLinkUp":"LibreLinkUp Serverbereich",
  "Serveur80":"Webserver läuft auf Port 80",
  "Update":"Aktualisierung",
  "UpdateComplete":"Aktualisierung abgeschlossen",
  "ParaConfig":"Konfigurationseinstellungen",
  "Historique":"Verlauf",
  "Luminosite":"Bildschirmhelligkeit nachts",
  "Rotation":"Bildschirmdrehung",
  "Refuse":"Ablehnen",
  "Accept":"Akzeptieren",
  "OKData":"Zugriff auf Daten erlaubt",
  "Clavier":"Tastatur",
  "PassWiFi":"WLAN-Passwort: ",
  "SetLibreLinkUp":"LibreLinkUp-Parameter festzulegen",
  "EmailLinkUp":"E-Mail des LibreLinkUp-Kontos",
  "PasseLinkUp":"Passwort des LibreLinkUp-Kontos",
  "Modifier":"Bearbeiten",
  "Tester":"Testen",
  "Password":"Passwort",
  "Undefined":"Nicht definiert",
  "ServerZone":"Server region",
  "ConnectOK":"Verbindung erfolgreich!",
  "UserUnknown":"Unbekannter Benutzer auf dem Server",
  "ServerNoAccess":"Server nicht erreichbar",
  "VersionSoft":"Softwareversion: ",
  "Auteur":"Autor",
  "AdrIP":"IP-Adresse: ",
  "NoWiFi":"WLAN nicht verbunden mit: ",
  "GlucoOn":"Gluco-Monitor läuft seit: ",
  "Cancel":"Abbrechen",
  "ListWiFi":"Liste der WLAN-Netzwerke",
  "byF1ATB":"von F1ATB",
  "Glucose":"Glukose",
  "dataLibreview":"Libreview-Daten",
  "dataDexcom":"Dexcom Share-Daten",
  "Arbo":"Klicken Sie auf {}, um die Baumstruktur zu öffnen oder zu schließen",
  "DisplayArbo":"Baumansicht der Libreview-JSON-Nachrichten",
  "DisplayArboDexcom":"Baumansicht der Dexcom Share-JSON-Nachrichten",
  "LogLibreview":"Libreview-Anmeldung",
  "LogDexcom":"Dexcom Share-Anmeldung",
  "ConnectLibreview":"Verbindung zu Libreview",
  "ConnectDexcom":"Verbindung zu Dexcom Share",
  "GraphLibreview":"Libreview-Diagramm",
  "GraphDexcom":"Dexcom Share-Diagramm",
  "UpdateOTA":"Software-Update über OTA",
  "VersionNow":"Ihre aktuelle Gluco-Monitor-Version: ",
  "VersionDispo":"Verfügbare Version(en): ",
  "Telecharge":"1 - Laden Sie die gewünschte Binärversion des Gluco-Monitors auf Ihren Computer herunter",
  "ClickBin":"durch Anklicken",
  "SelectFile":"2 - Klicken Sie auf 'Datei auswählen' und wählen Sie diese Binärdatei auf Ihrem Computer aus",
  "SendBin":"3 - Klicken Sie auf ",
  "SendBinBut":"Binärdatei senden",
  "AutoOnMonitor":"Zugriff auf dem Monitor erlauben",
  "SensorType":"Sensortyp",
  "GlucoseUnit":"Glukoseeinheit",
  "CouleurGlycemie":"Glukosefarbe",
  "Blanc":"Weiß",
  "Couleur":"Farbe",
  "SetDexcom":"Dexcom-Parameter festlegen",
  "UsernameDexcom":"Dexcom Share Benutzername",
  "PasseDexcom":"Dexcom Share Passwort",
  "Username":"Benutzername",
  "Region":"Region",
  "DexcomIndefini":"Dexcom-Konto nicht definiert",
  "ChartLimits":"Diagrammeinstellungen",
  "SetupOnScreen":"Am Bildschirm konfigurieren",
  "SetupAP":"Uber Wi-Fi konfigurieren",
  "APConnect":"Mit diesem WLAN-Netzwerk verbinden:",
  "APPassword":"Passwort: monitor1",
  "APOpenBrowser":"Dann im Browser oeffnen:"
}
)====";

