#pragma once
inline const char *LangEN = R"====(
{
  "Age":"Age",
  "AgeGlyc":"Glucose Age",
  "Compte":"Account",
  "Display":"Display",
  "Infos":"Information",
  "Lang":"Language",
  "F_Hor":"Time Zone",
  "Apropos":"About",
  "Restart":"Restart",
  "InitWifi":"WiFi Initialization",
  "Version":"Version: ",
  "Nom_WiFi": "WiFi Network: ",
  "MotDePasse":"Password: ",
  "RechercheWiFi":"WiFi Scan:",
  "ConnectedWiFi":"Connected via WiFi, IP address: ",
  "ou":" or ",
  "EchecWiFi":"WiFi connection failed",
  "SelectWifi":"Select WiFi",
  "ScanStart":"Scanning networks",
  "ScanTermine":"Scan complete",
  "PasReseau":"No WiFi network found",
  "reseauxTrouves":" networks found",
  "WaitGluco":"Waiting for glucose",
  "ConfNul":"Incomplete configuration",
  "LoginFailed":" Unable to connect to Libreview, HTTP code: ",
  "LastGlyco":" Last known glucose: ",
  "le":" on ",
  "GlucoFailed":" No glucose data from Libreview, HTTP code: ",
  "GraphFailed":" No graph from Libreview, HTTP code: ",
  "NoRecentGluco":"No recent glucose",
  "LinkUpIndefini":"LibreLinkUp account not defined",
  "ZoneLinkUp":"LibreLinkUp server region",
  "Serveur80":"Web server running on port 80",
  "Update":"Update",
  "UpdateComplete":"Update completed",
  "ParaConfig":"Configuration Settings",
  "Historique":"History",
  "Luminosite":"Night screen brightness",
  "LuminositeJour":"Day brightness",
  "DayStartsAt":"Day starts at",
  "NightStartsAt":"Night starts at",
  "Rotation":"Screen rotation",
  "Refuse":"Refuse",
  "Accept":"Accept",
  "OKData":"Data access authorized",
  "Clavier":"Keyboard",
  "PassWiFi":"WiFi network password: ",
  "SetLibreLinkUp":"Set LibreLinkUp parameters",
  "EmailLinkUp":"LibreLinkUp account email",
  "PasseLinkUp":"LibreLinkUp account password",
  "Modifier":"Edit",
  "Tester":"Test",
  "Password":"Password",
  "Undefined":"Undefined",
  "ServerZone":"Server region",
  "ConnectOK":"Connection successful!",
  "UserUnknown":"Unknown user on server",
  "ServerNoAccess":"Server unreachable",
  "VersionSoft":"Software version: ",
  "Auteur":"Author",
  "AdrIP":"IP Address: ",
  "NoWiFi":"WiFi not connected to: ",
  "GlucoOn":"Gluco-Monitor running since: ",
  "Cancel":"Cancel",
  "ListWiFi":"WiFi network list",
  "byF1ATB":"by F1ATB",
  "Glucose":"Glucose",
  "dataLibreview":"Libreview data",
  "dataDexcom":"Dexcom Share data",
  "Arbo":"Click {} to expand or collapse the tree",
  "DisplayArbo":"Libreview JSON message tree view",
  "DisplayArboDexcom":"Dexcom Share JSON message tree view",
  "LogLibreview":"Libreview login",
  "LogDexcom":"Dexcom Share login",
  "ConnectLibreview":"Connecting to Libreview",
  "ConnectDexcom":"Connecting to Dexcom Share",
  "GraphLibreview":"Libreview graph",
  "GraphDexcom":"Dexcom Share graph",
  "UpdateOTA":"Software update via OTA",
  "VersionNow":"Your current Gluco-Monitor version: ",
  "VersionDispo":"Available version(s): ",
  "Telecharge":"1 - Download the desired Gluco-Monitor binary version to your computer",
  "ClickBin":"by clicking on it",
  "SelectFile":"2 - Click 'Choose a file' and select this binary on your computer",
  "SendBin":"3 - Click ",
  "SendBinBut":"Send binary",
  "AutoOnMonitor":"Authorize access on the monitor",
  "SensorType":"Sensor Type",
  "GlucoseUnit":"Glucose Unit",
  "CouleurGlycemie":"Glucose color",
  "Blanc":"White",
  "Couleur":"Color",
  "SetDexcom":"Set Dexcom parameters",
  "UsernameDexcom":"Dexcom Share username",
  "PasseDexcom":"Dexcom Share password",
  "Username":"Username",
  "Region":"Region",
  "DexcomIndefini":"Dexcom account not defined",
  "ChartLimits":"Chart Limits",
  "SetupOnScreen":"Configure on-screen",
  "SetupAP":"Configure over Wi-Fi",
  "APConnect":"Connect to this Wi-Fi network:",
  "APPassword":"Password: monitor1",
  "APOpenBrowser":"Then open in your browser:",
  "NightScoutIndefini":"NightScout account not defined",
  "SetNightScout":"Set NightScout parameters",
  "NightScoutURL":"NightScout URL",
  "NightScoutToken":"Access Token"
}
)====";