#pragma once
inline const char *LangES = R"====(
{
  "Age":"Edad",
  "AgeGlyc":"Edad de la glucemia",
  "Compte":"Cuenta",
  "Display":"Pantalla",
  "Infos":"Información",
  "Lang":"Idioma",
  "F_Hor":"Zona horaria",
  "Apropos":"Acerca de",
  "Restart":"Reiniciar",
  "InitWifi":"Inicialización de WiFi",
  "Version":"Versión: ",
  "Nom_WiFi": "Red WiFi: ",
  "MotDePasse":"Contraseña: ",
  "RechercheWiFi":"Búsqueda WiFi:",
  "ConnectedWiFi":"Conectado por WiFi, dirección IP: ",
  "ou":" o ",
  "EchecWiFi":"Error de conexión WiFi",
  "SelectWifi":"Seleccionar WiFi",
  "ScanStart":"Escaneando redes",
  "ScanTermine":"Escaneo finalizado",
  "PasReseau":"No se encontró ninguna red WiFi",
  "reseauxTrouves":" redes encontradas",
  "WaitGluco":"Esperando glucemia",
  "ConfNul":"Configuración incompleta",
  "LoginFailed":" Sin conexión a Libreview, código HTTP: ",
  "LastGlyco":" Última glucemia conocida: ",
  "le":" el ",
  "GlucoFailed":" Sin datos de glucemia de Libreview, código HTTP: ",
  "GraphFailed":" Sin gráfico de Libreview, código HTTP: ",
  "NoRecentGluco":"No hay glucemia reciente",
  "LinkUpIndefini":"Cuenta LibreLinkUp no definida",
  "ZoneLinkUp":"Zona del servidor LibreLinkUp",
  "Serveur80":"Servidor web activo en el puerto 80",
  "Update":"Actualización",
  "UpdateComplete":"Actualización completada",
  "ParaConfig":"Parámetros de configuración",
  "Historique":"Historial",
  "Luminosite":"Brillo de pantalla nocturna",
  "Rotation":"Rotación de pantalla",
  "Refuse":"Rechazar",
  "Accept":"Aceptar",
  "OKData":"Acceso a los datos autorizado",
  "Clavier":"Teclado",
  "PassWiFi":"Contraseña de la red WiFi: ",
  "SetLibreLinkUp":"Configurar los parámetros de LibreLinkUp",
  "EmailLinkUp":"Email de la cuenta LibreLinkUp",
  "PasseLinkUp":"Contraseña de la cuenta LibreLinkUp",
  "Modifier":"Modificar",
  "Tester":"Probar",
  "Password":"Contraseña",
  "Undefined":"No definido",
  "ServerZone":"Zona del servidor",
  "ConnectOK":"¡Conexión exitosa!",
  "UserUnknown":"Usuario desconocido en el servidor",
  "ServerNoAccess":"Servidor inaccesible",
  "VersionSoft":"Versión del software: ",
  "Auteur":"Autor",
  "AdrIP":"Dirección IP: ",
  "NoWiFi":"WiFi no conectado a: ",
  "GlucoOn":"Gluco-Monitor activo desde: ",
  "Cancel":"Cancelar",
  "ListWiFi":"Lista de redes WiFi",
  "byF1ATB":"por F1ATB",
  "Glucose":"Glucemia",
  "dataLibreview":"Datos Libreview",
  "dataDexcom":"Datos Dexcom Share",
  "Arbo":"Haz clic en {} para abrir o cerrar el árbol",
  "DisplayArbo":"Visualización en árbol de los mensajes JSON de Libreview",
  "DisplayArboDexcom":"Visualización en árbol de los mensajes JSON de Dexcom Share",
  "LogLibreview":"Inicio de sesión en Libreview",
  "LogDexcom":"Inicio de sesión en Dexcom Share",
  "ConnectLibreview":"Conexión a Libreview",
  "ConnectDexcom":"Conexión a Dexcom Share",
  "GraphLibreview":"Gráfico de Libreview",
  "GraphDexcom":"Gráfico de Dexcom Share",
  "UpdateOTA":"Actualización de software por OTA",
  "VersionNow":"Tu versión actual de Gluco-Monitor: ",
  "VersionDispo":"Versión(es) disponible(s): ",
  "Telecharge":"1 - Descarga en tu ordenador la versión binaria deseada de Gluco-Monitor",
  "ClickBin":"haciendo clic en ella",
  "SelectFile":"2 - Haz clic en 'Elegir archivo' y selecciona este binario en tu ordenador",
  "SendBin":"3 - Haz clic en ",
  "SendBinBut":"Enviar binario",
  "AutoOnMonitor":"Autoriza el acceso en el monitor",
  "SensorType":"Tipo de Sensor",
  "GlucoseUnit":"Unidad de glucosa",
  "CouleurGlycemie":"Color de la glucosa",
  "Blanc":"Blanco",
  "Couleur":"Color",
  "SetDexcom":"Configurar parámetros de Dexcom",
  "UsernameDexcom":"Nombre de usuario Dexcom Share",
  "PasseDexcom":"Contraseña Dexcom Share",
  "Username":"Nombre de usuario",
  "Region":"Región",
  "DexcomIndefini":"Cuenta Dexcom no definida",
  "ChartLimits":"Configuracion del grafico"
}
)====";