#pragma once
inline const char *LangFR = R"====(
{
  "Age":"Age",
  "AgeGlyc":"Age Glycémie",
  "Compte":"Compte",
  "Display":"Affichage",
  "Infos":"Informations",
  "Lang":"Langue",
  "F_Hor":"Fuseau Horaire",
  "Apropos":"A propos",
  "Restart":"Redémarrage",
  "InitWifi":"Initialisation du Wifi",
  "Version":"Version : ",
  "Nom_WiFi": "Réseau WiFi : ",
  "MotDePasse":"Mot de Passe : ",
  "RechercheWiFi":"Recherche WiFi :",
  "ConnectedWiFi":"Connecté par WiFi, addresse IP : ",
  "ou":" ou ",
  "EchecWiFi":"Echec de connexion au WiFi",
  "SelectWifi":"Selectionner le WiFi",
  "ScanStart":"Scan réseaux en cours",
  "ScanTermine":"Scan terminé",
  "PasReseau":"Pas de réseau WiFi trouvé",
  "reseauxTrouves":" réseaux trouvés",
  "WaitGluco":"Attente glycémie",
  "ConfNul":"Configuration incomplète",
  "LoginFailed":" Pas de connexion à Libreview, HTTP code : ",
  "LastGlyco":" Dernière Glycémie connue : ",
  "le":" le ",
  "GlucoFailed":" Pas de glycémie de Libreview, HTTP code : ",
  "GraphFailed":" Pas de graphique de Libreview, HTTP code : ",
  "NoRecentGluco":"Pas de glycémie récente",
  "LinkUpIndefini":"Compte LibreLinkUp non défini",
  "ZoneLinkUp":"Zone serveur LibreLinkUp",
  "Serveur80":"Serveur Web actif sur le port 80",
  "Update":"Mise à jour",
  "UpdateComplete":"Mise à jour terminée",
  "ParaConfig":"Paramètres de Configuration",
  "Historique":"Historique",
  "Luminosite":"Luminosité écran de nuit",
  "Rotation":"Rotation écran",
  "Refuse":"Refuser",
  "Accept":"Accepter",
  "OKData":"Autorisation accès aux données",
  "Clavier":"Clavier",
  "PassWiFi":"Mot de passe du réseau WiFi : ",
  "SetLibreLinkUp":"Définir les paramètres LibreLinkUp",
  "EmailLinkUp":"Email du compte LibreLinkUp",
  "PasseLinkUp":"Mot de passe du compte LibreLinkUp",
  "Modifier":"Modifier",
  "Tester":"Tester",
  "Password":"Mot de passe",
  "Undefined":"Non définie",
  "ServerZone":"Zone serveur",
  "ConnectOK":"Connexion réussie !",
  "UserUnknown":"Utilisateur inconnu sur le serveur",
  "ServerNoAccess":"Serveur innacessible",
  "VersionSoft":"Version logicielle : ",
  "Auteur":"Auteur",
  "AdrIP":"Adresse IP : ",
  "NoWiFi":"WiFi non connecté à : ",
  "GlucoOn":"Gluco-Monitor On depuis : ",
  "Cancel":"Annuler",
  "ListWiFi":"Liste des réseaux WiFi",
  "byF1ATB":"de F1ATB",
  "Glucose":"Glycémie",
  "dataLibreview":"Données Libreview",
  "dataDexcom":"Données Dexcom Share",
  "Arbo":"Cliquez sur {} pour ouvrir ou fermer l'arborescence",
  "DisplayArbo":"Affichage Arborescent Messages Libreview JSON",
  "DisplayArboDexcom":"Affichage Arborescent Messages Dexcom Share JSON",
  "LogLibreview":"Login à Libreview",
  "LogDexcom":"Login à Dexcom Share",
  "ConnectLibreview":"Connexion à Libreview",
  "ConnectDexcom":"Connexion à Dexcom Share",
  "GraphLibreview":"Graphe de Libreview",
  "GraphDexcom":"Graphe de Dexcom Share",
  "UpdateOTA":"Mise à jour logiciel par OTA",
  "VersionNow":"Votre version actuelle de Gluco-Monitor : ",
  "VersionDispo":"Version(s) disponible(s) : ",
  "Telecharge":"1 - Téléchargez sur votre ordinateur, la version binaire du logiciel du Gluco-Monitor souhaitée",
  "ClickBin":"en cliquant dessus",
  "SelectFile":"2 - Cliquez sur 'Choisir un fichier' et sélectionnez ce binaire sur votre ordinateur",
  "SendBin":"3 - Cliquez sur ",
  "SendBinBut":"Envoyer le binaire",
  "AutoOnMonitor":"Autorisez l'accès sur le moniteur",
  "SensorType":"Type de Capteur",
  "GlucoseUnit":"Unité du glucose",
  "CouleurGlycemie":"Couleur de la glycémie",
  "Blanc":"Blanc",
  "Couleur":"Couleur",
  "SetDexcom":"Définir les paramètres Dexcom",
  "UsernameDexcom":"Nom d'utilisateur Dexcom Share",
  "PasseDexcom":"Mot de passe Dexcom Share",
  "Username":"Nom d'utilisateur",
  "Region":"Région",
  "DexcomIndefini":"Compte Dexcom non défini",
  "ChartLimits":"Graphique",
  "SetupOnScreen":"Configurer sur l'ecran",
  "SetupAP":"Configurer via Wi-Fi",
  "APConnect":"Connectez-vous a ce reseau WiFi:",
  "APPassword":"Mot de passe: monitor1",
  "APOpenBrowser":"Puis ouvrez dans votre navigateur:",
  "NightScoutIndefini":"Compte NightScout non défini",
  "SetNightScout":"Définir les paramètres NightScout",
  "NightScoutURL":"URL NightScout",
  "NightScoutToken":"Jeton d'accès"
}
)====";