#pragma once
inline const char *LangPL = R"====(
{
  "Age":"Wiek",
  "AgeGlyc":"Wiek pomiaru",
  "Compte":"Konto",
  "Display":"Wyswietlanie",
  "Infos":"Informacje",
  "Lang":"Jezyk",
  "F_Hor":"Strefa czasowa",
  "Apropos":"O aplikacji",
  "Restart":"Restart",
  "InitWifi":"Inicjalizacja WiFi",
  "Version":"Wersja: ",
  "Nom_WiFi":"Siec WiFi: ",
  "MotDePasse":"Haslo: ",
  "RechercheWiFi":"Szukanie WiFi:",
  "ConnectedWiFi":"Polaczono przez WiFi, adres IP: ",
  "ou":" lub ",
  "EchecWiFi":"Blad polaczenia z WiFi",
  "SelectWifi":"Wybierz siec WiFi",
  "ScanStart":"Skanowanie sieci...",
  "ScanTermine":"Skanowanie zakonczone",
  "PasReseau":"Nie znaleziono sieci WiFi",
  "reseauxTrouves":" sieci znalezionych",
  "WaitGluco":"Oczekiwanie na pomiar",
  "ConfNul":"Konfiguracja niekompletna",
  "LoginFailed":" Brak polaczenia z Libreview, kod HTTP: ",
  "LastGlyco":" Ostatni znany pomiar: ",
  "le":" dnia ",
  "GlucoFailed":" Brak pomiaru z Libreview, kod HTTP: ",
  "GraphFailed":" Brak wykresu z Libreview, kod HTTP: ",
  "NoRecentGluco":"Brak aktualnego pomiaru",
  "LinkUpIndefini":"Konto LibreLinkUp niezdefiniowane",
  "ZoneLinkUp":"Strefa serwera LibreLinkUp",
  "Serveur80":"Serwer WWW aktywny na porcie 80",
  "Update":"Aktualizacja",
  "UpdateComplete":"Aktualizacja zakonczona",
  "ParaConfig":"Ustawienia konfiguracji",
  "Historique":"Historia",
  "Luminosite":"Jasnosc ekranu nocnego",
  "Rotation":"Obrot ekranu",
  "Refuse":"Odrzuc",
  "Accept":"Akceptuj",
  "OKData":"Autoryzacja dostepu do danych",
  "Clavier":"Klawiatura",
  "PassWiFi":"Haslo sieci WiFi: ",
  "SetLibreLinkUp":"Ustaw parametry LibreLinkUp",
  "EmailLinkUp":"Email konta LibreLinkUp",
  "PasseLinkUp":"Haslo konta LibreLinkUp",
  "Modifier":"Edytuj",
  "Tester":"Testuj",
  "Password":"Haslo",
  "Undefined":"Niezdefiniowane",
  "ServerZone":"Strefa serwera",
  "ConnectOK":"Polaczenie udane!",
  "UserUnknown":"Nieznany uzytkownik na serwerze",
  "ServerNoAccess":"Serwer niedostepny",
  "VersionSoft":"Wersja oprogramowania: ",
  "Auteur":"Autor",
  "AdrIP":"Adres IP: ",
  "NoWiFi":"WiFi niepodlaczone do: ",
  "GlucoOn":"Gluco-Monitor wlaczony od: ",
  "Cancel":"Anuluj",
  "ListWiFi":"Lista sieci WiFi",
  "byF1ATB":"od F1ATB",
  "Glucose":"Glukoza",
  "dataLibreview":"Dane Libreview",
  "dataDexcom":"Dane Dexcom Share",
  "Arbo":"Kliknij {} aby rozwinac lub zwinac drzewo",
  "DisplayArbo":"Widok drzewa wiadomosci Libreview JSON",
  "DisplayArboDexcom":"Widok drzewa wiadomosci Dexcom Share JSON",
  "LogLibreview":"Logowanie do Libreview",
  "LogDexcom":"Logowanie do Dexcom Share",
  "ConnectLibreview":"Polaczenie z Libreview",
  "ConnectDexcom":"Polaczenie z Dexcom Share",
  "GraphLibreview":"Wykres z Libreview",
  "GraphDexcom":"Wykres z Dexcom Share",
  "UpdateOTA":"Aktualizacja OTA",
  "VersionNow":"Twoja aktualna wersja Gluco-Monitor: ",
  "VersionDispo":"Dostepne wersje: ",
  "Telecharge":"1 - Pobierz na komputer wybrana wersje binarna Gluco-Monitor",
  "ClickBin":"klikajac na nia",
  "SelectFile":"2 - Kliknij 'Wybierz plik' i wskaz plik binarny na swoim komputerze",
  "SendBin":"3 - Kliknij ",
  "SendBinBut":"Wyslij plik binarny",
  "AutoOnMonitor":"Autoryzuj dostep na monitorze",
  "SensorType":"Typ czujnika",
  "GlucoseUnit":"Jednostka glukozy",
  "CouleurGlycemie":"Kolor wartosci glukozy",
  "Blanc":"Bialy",
  "Couleur":"Kolor",
  "SetDexcom":"Ustaw parametry Dexcom",
  "UsernameDexcom":"Nazwa uzytkownika Dexcom Share",
  "PasseDexcom":"Haslo Dexcom Share",
  "Username":"Nazwa uzytkownika",
  "Region":"Region",
  "DexcomIndefini":"Konto Dexcom niezdefiniowane",
  "ChartLimits":"Ustawienia wykresu",
  "SetupOnScreen":"Konfiguruj na ekranie",
  "SetupAP":"Konfiguruj przez Wi-Fi",
  "APConnect":"Polacz sie z ta siecia WiFi:",
  "APPassword":"Haslo: monitor1",
  "APOpenBrowser":"Nastepnie otworz w przegladarce:",
  "NightScoutIndefini":"Konto NightScout niezdefiniowane",
  "SetNightScout":"Ustaw parametry NightScout",
  "NightScoutURL":"URL NightScout",
  "NightScoutToken":"Token dostępu"
}
)====";