#pragma once
inline const char *LangPL = R"====(
{
  "Age":"Wiek",
  "AgeGlyc":"Wiek pomiaru",
  "Compte":"Konto",
  "Display":"Wyświetlanie",
  "Infos":"Informacje",
  "Lang":"Język",
  "F_Hor":"Strefa czasowa",
  "Apropos":"O aplikacji",
  "Restart":"Restart",
  "InitWifi":"Inicjalizacja WiFi",
  "Version":"Wersja: ",
  "Nom_WiFi":"Sieć WiFi: ",
  "MotDePasse":"Hasło: ",
  "RechercheWiFi":"Szukanie WiFi:",
  "ConnectedWiFi":"Połączono przez WiFi, adres IP: ",
  "ou":" lub ",
  "EchecWiFi":"Błąd połączenia z WiFi",
  "SelectWifi":"Wybierz sieć WiFi",
  "ScanStart":"Skanowanie sieci...",
  "ScanTermine":"Skanowanie zakończone",
  "PasReseau":"Nie znaleziono sieci WiFi",
  "reseauxTrouves":" sieci znalezionych",
  "WaitGluco":"Oczekiwanie na pomiar",
  "ConfNul":"Konfiguracja niekompletna",
  "LoginFailed":" Brak połączenia z Libreview, kod HTTP: ",
  "LastGlyco":" Ostatni znany pomiar: ",
  "le":" dnia ",
  "GlucoFailed":" Brak pomiaru z Libreview, kod HTTP: ",
  "GraphFailed":" Brak wykresu z Libreview, kod HTTP: ",
  "NoRecentGluco":"Brak aktualnego pomiaru",
  "LinkUpIndefini":"Konto LibreLinkUp niezdefiniowane",
  "ZoneLinkUp":"Strefa serwera LibreLinkUp",
  "Serveur80":"Serwer WWW aktywny na porcie 80",
  "Update":"Aktualizacja",
  "UpdateComplete":"Aktualizacja zakończona",
  "ParaConfig":"Ustawienia konfiguracji",
  "Historique":"Historia",
  "Luminosite":"Jasność w nocy",
  "LuminositeJour":"Jasność w dzień",
  "DayStartsAt":"Początek dnia",
  "NightStartsAt":"Początek nocy",
  "Rotation":"Obrót ekranu",
  "Refuse":"Odrzuć",
  "Accept":"Akceptuj",
  "OKData":"Autoryzacja dostępu do danych",
  "Clavier":"Klawiatura",
  "PassWiFi":"Hasło sieci WiFi: ",
  "SetLibreLinkUp":"Ustaw parametry LibreLinkUp",
  "EmailLinkUp":"Email konta LibreLinkUp",
  "PasseLinkUp":"Hasło konta LibreLinkUp",
  "Modifier":"Edytuj",
  "Tester":"Testuj",
  "Password":"Hasło",
  "Undefined":"Niezdefiniowane",
  "ServerZone":"Strefa serwera",
  "ConnectOK":"Połączenie udane!",
  "UserUnknown":"Nieznany użytkownik na serwerze",
  "ServerNoAccess":"Serwer niedostępny",
  "VersionSoft":"Wersja oprogramowania: ",
  "Auteur":"Autor",
  "AdrIP":"Adres IP: ",
  "NoWiFi":"WiFi niepodłączone do: ",
  "GlucoOn":"Gluco-Monitor włączony od: ",
  "Cancel":"Anuluj",
  "ListWiFi":"Lista sieci WiFi",
  "byF1ATB":"od F1ATB",
  "Glucose":"Glukoza",
  "dataLibreview":"Dane Libreview",
  "dataDexcom":"Dane Dexcom Share",
  "Arbo":"Kliknij {} aby rozwinąć lub zwinąć drzewo",
  "DisplayArbo":"Widok drzewa wiadomości Libreview JSON",
  "DisplayArboDexcom":"Widok drzewa wiadomości Dexcom Share JSON",
  "LogLibreview":"Logowanie do Libreview",
  "LogDexcom":"Logowanie do Dexcom Share",
  "ConnectLibreview":"Połączenie z Libreview",
  "ConnectDexcom":"Połączenie z Dexcom Share",
  "GraphLibreview":"Wykres z Libreview",
  "GraphDexcom":"Wykres z Dexcom Share",
  "UpdateOTA":"Aktualizacja OTA",
  "VersionNow":"Twoja aktualna wersja Gluco-Monitor: ",
  "VersionDispo":"Dostępne wersje: ",
  "Telecharge":"1 - Pobierz na komputer wybraną wersję binarną Gluco-Monitor",
  "ClickBin":"klikając na nią",
  "SelectFile":"2 - Kliknij 'Wybierz plik' i wskaż plik binarny na swoim komputerze",
  "SendBin":"3 - Kliknij ",
  "SendBinBut":"Wyślij plik binarny",
  "AutoOnMonitor":"Autoryzuj dostęp na monitorze",
  "SensorType":"Typ czujnika",
  "GlucoseUnit":"Jednostka glukozy",
  "CouleurGlycemie":"Kolor wartości glukozy",
  "Blanc":"Biały",
  "Couleur":"Kolor",
  "SetDexcom":"Ustaw parametry Dexcom",
  "UsernameDexcom":"Nazwa użytkownika Dexcom Share",
  "PasseDexcom":"Hasło Dexcom Share",
  "Username":"Nazwa użytkownika",
  "Region":"Region",
  "DexcomIndefini":"Konto Dexcom niezdefiniowane",
  "ChartLimits":"Ustawienia wykresu",
  "SetupOnScreen":"Konfiguruj na ekranie",
  "SetupAP":"Konfiguruj przez Wi-Fi",
  "APConnect":"Połącz się z tą siecią WiFi:",
  "APPassword":"Hasło: monitor1",
  "APOpenBrowser":"Następnie otwórz w przeglądarce:",
  "NightScoutIndefini":"Konto NightScout niezdefiniowane",
  "SetNightScout":"Ustaw parametry NightScout",
  "NightScoutURL":"URL NightScout",
  "NightScoutToken":"Token dostępu",
  "NightScoutInterval":"Interwał aktualizacji"
}
)====";